In [2]:
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE

In [3]:
data = pd.read_csv('6dof_disc_and_classification.csv')
data.drop('Unnamed: 0', inplace=True, axis=1)
data['class'] = np.where(data['Success_Rates'] > 0, 1, 0)

In [4]:
data

,Success_Rates,Joint2 type_pitch,Joint2 type_pris,Joint2 type_roll,Joint3 type_pitch,Joint3 type_pris,Joint3 type_roll,Joint4 type_pitch,Joint4 type_pris,Joint4 type_roll,...,Link4 length_0.7,Link5 length_0.1,Link5 length_0.3,Link5 length_0.5,Link5 length_0.7,Link6 length_0.1,Link6 length_0.3,Link6 length_0.5,Link6 length_0.7,class
0,0,1,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0
1,0,1,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
2,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
3,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
4,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102535,2,0,0,1,0,0,1,0,1,0,...,0,1,0,0,0,1,0,0,0,1
102536,7,0,0,1,0,0,1,0,1,0,...,0,1,0,0,0,0,1,0,0,1
102537,0,0,0,1,0,0,1,0,1,0,...,0,1,0,0,0,1,0,0,0,0
102538,10,0,0,1,0,0,1,0,0,1,...,0,1,0,0,0,0,1,0,0,1
102539,10,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,1,0,0,0,1

In [6]:
X = data.drop(columns=['Success_Rates', 'class'], axis=1)
y = data[['class']]
print('Initial dataset shape %s' % y["class"].value_counts())
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X, y)
print('Over Resampled dataset shape %s' % y_res["class"].value_counts())

Initial dataset shape 0    73159
1    29381
Name: class, dtype: int64
Over Resampled dataset shape 0    73159
1    73159
Name: class, dtype: int64

In [15]:
X_res.loc[X_res['Joint3 type_pris']==0.3]

Empty DataFrame
Columns: [Joint2 type_pitch, Joint2 type_pris, Joint2 type_roll, Joint3 type_pitch, Joint3 type_pris, Joint3 type_roll, Joint4 type_pitch, Joint4 type_pris, Joint4 type_roll, Joint5 type_pitch, Joint5 type_pris, Joint5 type_roll, Joint6 type_pitch, Joint6 type_pris, Joint6 type_roll, Joint2 axis_y, Joint2 axis_z, Joint3 axis_x, Joint3 axis_y, Joint3 axis_z, Joint4 axis_x, Joint4 axis_y, Joint4 axis_z, Joint5 axis_x, Joint5 axis_y, Joint5 axis_z, Joint6 axis_x, Joint6 axis_y, Joint6 axis_z, Link2 length_0.1, Link2 length_0.3, Link2 length_0.5, Link2 length_0.7, Link3 length_0.1, Link3 length_0.3, Link3 length_0.5, Link3 length_0.7, Link4 length_0.1, Link4 length_0.3, Link4 length_0.5, Link4 length_0.7, Link5 length_0.1, Link5 length_0.3, Link5 length_0.5, Link5 length_0.7, Link6 length_0.1, Link6 length_0.3, Link6 length_0.5, Link6 length_0.7]
Index: []

[0 rows x 49 columns]